// generated by stringer -type=Option; DO NOT EDIT

package grok

import "fmt"

const _Option_name = "DEFAULTCAPTURENAMEDCAPTURENODEFAULTPATTERNS"

var _Option_index = [...]uint8{0, 14, 26, 43}

func (i Option) String() string {
	if i+1 >= Option(len(_Option_index)) {
		return fmt.Sprintf("Option(%d)", i)
	}
	return _Option_name[_Option_index[i]:_Option_index[i+1]]
}
